name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format 22
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key |
          sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc

          echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-22 main" |
          sudo tee /etc/apt/sources.list.d/llvm.list

          sudo apt-get update
          sudo apt-get install -y clang-format-22

      - name: Check formatting
        run: |
          find include src tests -type f \( -name "*.cpp" -o -name "*.hpp" \) \
          -exec clang-format-22 --dry-run --Werror {} +
          clang-format-22 --dry-run --Werror main.cpp

  build:
    name: Windows build and tests
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        shell: pwsh
        run: |
          cmake -S . -B build `
            -G "Visual Studio 18 2026" `
            -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        shell: pwsh
        run: cmake --build build --config Release

      - name: Run tests
        shell: pwsh
        run: .\build\Release\skoll_tests.exe